### ISSUE TITLE
Responsive image formats

### ISSUE THREAD

**Issue by vsandvold** [finn-no/spaden#43]
We started using responsive image format components in mfinn, and need to add some more functionality for this in spaden.

Here's the suggested markup:
```html
<div class="image-holder normal-format">
    <img class="centered-element nocrop" src="...">
</div>
```

And here's styling for the different image formats:
```css
.image-holder {
    overflow: hidden;
    position: relative;
}
.centered-element {
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    margin: auto;
}
.nocrop {
    max-height: 100%;
    max-width: 100%;
}
.normal-format {
    padding-top: 74.5%;
}
.professional-format {
    padding-top: 66.67%;
}
.widescreen-format {
    padding-top: 56.25%;
}
.logo-format {
    padding-top: 50%;
    max-width: 75%;
}
```
